export const rows = [
  {
    kst: 82529,
    department: "Marketing",
    locked: false,
    group: "Group D",
    company: "Acme Corporation",
  },
  {
    kst: 51762,
    department: "Product Management",
    locked: true,
    group: "Group F",
    company: "Innovative Solutions",
  },
  {
    kst: 80099,
    department: "Sales",
    locked: true,
    group: "Group B",
    company: "Acme Corporation",
  },
  {
    kst: 76017,
    department: "Research and Development",
    locked: true,
    group: "Group A",
    company: "Acme Corporation",
  },
  {
    kst: 42804,
    department: "Engineering",
    locked: true,
    group: "Group J",
    company: "Sunshine Group",
  },
  {
    kst: 31225,
    department: "Services",
    locked: true,
    group: "Group D",
    company: "Acme Corporation",
  },
  {
    kst: 84652,
    department: "Legal",
    locked: false,
    group: "Group A",
    company: "Innovative Solutions",
  },
  {
    kst: 26525,
    department: "Support",
    locked: true,
    group: "Group A",
    company: "XYZ Industries",
  },
  {
    kst: 60838,
    department: "Product Management",
    locked: true,
    group: "Group H",
    company: "Sunshine Group",
  },
  {
    kst: 13025,
    department: "Engineering",
    locked: false,
    group: "Group G",
    company: "Global Enterprises",
  },
  {
    kst: 81547,
    department: "Research and Development",
    locked: true,
    group: "Group B",
    company: "Global Enterprises",
  },
  {
    kst: 50620,
    department: "Services",
    locked: true,
    group: "Group B",
    company: "Global Enterprises",
  },
  {
    kst: 88385,
    department: "Human Resources",
    locked: false,
    group: "Group H",
    company: "Sunshine Group",
  },
  {
    kst: 97203,
    department: "Training",
    locked: false,
    group: "Group E",
    company: "Global Enterprises",
  },
  {
    kst: 22538,
    department: "Legal",
    locked: true,
    group: "Group D",
    company: "Innovative Solutions",
  },
  {
    kst: 82539,
    department: "Legal",
    locked: true,
    group: "Group H",
    company: "Innovative Solutions",
  },
  {
    kst: 57494,
    department: "Support",
    locked: false,
    group: "Group D",
    company: "XYZ Industries",
  },
  {
    kst: 49027,
    department: "Business Development",
    locked: true,
    group: "Group F",
    company: "Sunshine Group",
  },
  {
    kst: 75638,
    department: "Marketing",
    locked: false,
    group: "Group J",
    company: "XYZ Industries",
  },
  {
    kst: 48464,
    department: "Research and Development",
    locked: true,
    group: "Group C",
    company: "Global Enterprises",
  },
  {
    kst: 42956,
    department: "Training",
    locked: false,
    group: "Group J",
    company: "Acme Corporation",
  },
  {
    kst: 76606,
    department: "Engineering",
    locked: true,
    group: "Group H",
    company: "Acme Corporation",
  },
  {
    kst: 10617,
    department: "Research and Development",
    locked: true,
    group: "Group G",
    company: "Innovative Solutions",
  },
  {
    kst: 79452,
    department: "Services",
    locked: false,
    group: "Group H",
    company: "Global Enterprises",
  },
  {
    kst: 77600,
    department: "Support",
    locked: true,
    group: "Group F",
    company: "Innovative Solutions",
  },
  {
    kst: 64569,
    department: "Product Management",
    locked: true,
    group: "Group C",
    company: "Innovative Solutions",
  },
  {
    kst: 24632,
    department: "Marketing",
    locked: false,
    group: "Group A",
    company: "Acme Corporation",
  },
  {
    kst: 59869,
    department: "Human Resources",
    locked: false,
    group: "Group B",
    company: "XYZ Industries",
  },
  {
    kst: 16212,
    department: "Engineering",
    locked: false,
    group: "Group A",
    company: "Global Enterprises",
  },
  {
    kst: 57787,
    department: "Support",
    locked: false,
    group: "Group B",
    company: "Acme Corporation",
  },
  {
    kst: 59444,
    department: "Sales",
    locked: true,
    group: "Group I",
    company: "Sunshine Group",
  },
  {
    kst: 67268,
    department: "Engineering",
    locked: false,
    group: "Group I",
    company: "Acme Corporation",
  },
  {
    kst: 86200,
    department: "Support",
    locked: true,
    group: "Group J",
    company: "XYZ Industries",
  },
  {
    kst: 36810,
    department: "Sales",
    locked: true,
    group: "Group E",
    company: "Global Enterprises",
  },
  {
    kst: 99131,
    department: "Support",
    locked: true,
    group: "Group H",
    company: "XYZ Industries",
  },
  {
    kst: 22769,
    department: "Support",
    locked: false,
    group: "Group G",
    company: "Innovative Solutions",
  },
  {
    kst: 81985,
    department: "Research and Development",
    locked: false,
    group: "Group H",
    company: "Acme Corporation",
  },
  {
    kst: 56150,
    department: "Business Development",
    locked: true,
    group: "Group D",
    company: "Innovative Solutions",
  },
  {
    kst: 51276,
    department: "Business Development",
    locked: true,
    group: "Group A",
    company: "XYZ Industries",
  },
  {
    kst: 35401,
    department: "Sales",
    locked: false,
    group: "Group D",
    company: "Innovative Solutions",
  },
  {
    kst: 93272,
    department: "Marketing",
    locked: true,
    group: "Group E",
    company: "Acme Corporation",
  },
  {
    kst: 24698,
    department: "Training",
    locked: false,
    group: "Group I",
    company: "Sunshine Group",
  },
  {
    kst: 36037,
    department: "Research and Development",
    locked: false,
    group: "Group I",
    company: "Global Enterprises",
  },
  {
    kst: 40371,
    department: "Sales",
    locked: true,
    group: "Group I",
    company: "Global Enterprises",
  },
  {
    kst: 75937,
    department: "Accounting",
    locked: false,
    group: "Group F",
    company: "XYZ Industries",
  },
  {
    kst: 64003,
    department: "Engineering",
    locked: false,
    group: "Group C",
    company: "XYZ Industries",
  },
  {
    kst: 40541,
    department: "Product Management",
    locked: false,
    group: "Group F",
    company: "Innovative Solutions",
  },
  {
    kst: 73586,
    department: "Training",
    locked: true,
    group: "Group F",
    company: "Innovative Solutions",
  },
  {
    kst: 68451,
    department: "Engineering",
    locked: true,
    group: "Group C",
    company: "Acme Corporation",
  },
  {
    kst: 80666,
    department: "Services",
    locked: false,
    group: "Group G",
    company: "XYZ Industries",
  },
  {
    kst: 31465,
    department: "Services",
    locked: false,
    group: "Group E",
    company: "Sunshine Group",
  },
  {
    kst: 50316,
    department: "Legal",
    locked: false,
    group: "Group F",
    company: "Acme Corporation",
  },
  {
    kst: 61227,
    department: "Marketing",
    locked: true,
    group: "Group F",
    company: "Global Enterprises",
  },
  {
    kst: 35557,
    department: "Research and Development",
    locked: false,
    group: "Group J",
    company: "Global Enterprises",
  },
  {
    kst: 56251,
    department: "Engineering",
    locked: true,
    group: "Group F",
    company: "Global Enterprises",
  },
  {
    kst: 73014,
    department: "Marketing",
    locked: false,
    group: "Group J",
    company: "Innovative Solutions",
  },
  {
    kst: 88273,
    department: "Research and Development",
    locked: true,
    group: "Group E",
    company: "XYZ Industries",
  },
  {
    kst: 47567,
    department: "Services",
    locked: true,
    group: "Group H",
    company: "XYZ Industries",
  },
  {
    kst: 32407,
    department: "Research and Development",
    locked: false,
    group: "Group F",
    company: "Sunshine Group",
  },
  {
    kst: 48917,
    department: "Human Resources",
    locked: false,
    group: "Group J",
    company: "Sunshine Group",
  },
  {
    kst: 13380,
    department: "Human Resources",
    locked: false,
    group: "Group H",
    company: "Sunshine Group",
  },
  {
    kst: 29270,
    department: "Business Development",
    locked: false,
    group: "Group B",
    company: "XYZ Industries",
  },
  {
    kst: 11591,
    department: "Support",
    locked: true,
    group: "Group H",
    company: "XYZ Industries",
  },
  {
    kst: 73144,
    department: "Marketing",
    locked: false,
    group: "Group G",
    company: "Global Enterprises",
  },
  {
    kst: 56815,
    department: "Product Management",
    locked: true,
    group: "Group C",
    company: "XYZ Industries",
  },
  {
    kst: 62806,
    department: "Business Development",
    locked: false,
    group: "Group A",
    company: "Sunshine Group",
  },
  {
    kst: 69876,
    department: "Accounting",
    locked: true,
    group: "Group C",
    company: "XYZ Industries",
  },
  {
    kst: 56112,
    department: "Human Resources",
    locked: false,
    group: "Group E",
    company: "Global Enterprises",
  },
  {
    kst: 99418,
    department: "Legal",
    locked: false,
    group: "Group G",
    company: "Global Enterprises",
  },
  {
    kst: 60786,
    department: "Accounting",
    locked: false,
    group: "Group J",
    company: "XYZ Industries",
  },
  {
    kst: 56489,
    department: "Accounting",
    locked: false,
    group: "Group F",
    company: "Sunshine Group",
  },
  {
    kst: 95086,
    department: "Accounting",
    locked: true,
    group: "Group G",
    company: "Innovative Solutions",
  },
  {
    kst: 31841,
    department: "Support",
    locked: false,
    group: "Group F",
    company: "XYZ Industries",
  },
  {
    kst: 22814,
    department: "Sales",
    locked: true,
    group: "Group I",
    company: "XYZ Industries",
  },
  {
    kst: 40425,
    department: "Accounting",
    locked: true,
    group: "Group H",
    company: "Innovative Solutions",
  },
  {
    kst: 62416,
    department: "Support",
    locked: false,
    group: "Group F",
    company: "XYZ Industries",
  },
  {
    kst: 36905,
    department: "Support",
    locked: false,
    group: "Group E",
    company: "Acme Corporation",
  },
  {
    kst: 49411,
    department: "Sales",
    locked: false,
    group: "Group B",
    company: "XYZ Industries",
  },
  {
    kst: 22826,
    department: "Human Resources",
    locked: true,
    group: "Group I",
    company: "Innovative Solutions",
  },
  {
    kst: 44395,
    department: "Human Resources",
    locked: false,
    group: "Group F",
    company: "XYZ Industries",
  },
  {
    kst: 24544,
    department: "Business Development",
    locked: false,
    group: "Group H",
    company: "Acme Corporation",
  },
  {
    kst: 94081,
    department: "Business Development",
    locked: true,
    group: "Group F",
    company: "Innovative Solutions",
  },
  {
    kst: 56252,
    department: "Support",
    locked: true,
    group: "Group I",
    company: "Innovative Solutions",
  },
  {
    kst: 54025,
    department: "Business Development",
    locked: true,
    group: "Group I",
    company: "Innovative Solutions",
  },
  {
    kst: 38528,
    department: "Marketing",
    locked: false,
    group: "Group C",
    company: "XYZ Industries",
  },
  {
    kst: 60876,
    department: "Training",
    locked: true,
    group: "Group H",
    company: "Innovative Solutions",
  },
  {
    kst: 87053,
    department: "Engineering",
    locked: false,
    group: "Group D",
    company: "Global Enterprises",
  },
  {
    kst: 53586,
    department: "Services",
    locked: true,
    group: "Group D",
    company: "Sunshine Group",
  },
  {
    kst: 52439,
    department: "Services",
    locked: false,
    group: "Group H",
    company: "Sunshine Group",
  },
  {
    kst: 21187,
    department: "Marketing",
    locked: true,
    group: "Group F",
    company: "Acme Corporation",
  },
  {
    kst: 85974,
    department: "Research and Development",
    locked: false,
    group: "Group F",
    company: "Sunshine Group",
  },
  {
    kst: 53910,
    department: "Legal",
    locked: false,
    group: "Group J",
    company: "Acme Corporation",
  },
  {
    kst: 70403,
    department: "Training",
    locked: false,
    group: "Group G",
    company: "XYZ Industries",
  },
  {
    kst: 92207,
    department: "Training",
    locked: false,
    group: "Group B",
    company: "XYZ Industries",
  },
  {
    kst: 76630,
    department: "Legal",
    locked: true,
    group: "Group I",
    company: "Global Enterprises",
  },
  {
    kst: 38022,
    department: "Support",
    locked: true,
    group: "Group J",
    company: "Global Enterprises",
  },
  {
    kst: 42631,
    department: "Sales",
    locked: false,
    group: "Group E",
    company: "Global Enterprises",
  },
  {
    kst: 34243,
    department: "Services",
    locked: true,
    group: "Group H",
    company: "Global Enterprises",
  },
  {
    kst: 98411,
    department: "Product Management",
    locked: false,
    group: "Group B",
    company: "Innovative Solutions",
  },
  {
    kst: 87719,
    department: "Support",
    locked: false,
    group: "Group I",
    company: "Acme Corporation",
  },
  {
    kst: 60004,
    department: "Human Resources",
    locked: true,
    group: "Group J",
    company: "XYZ Industries",
  },
  {
    kst: 56666,
    department: "Marketing",
    locked: false,
    group: "Group B",
    company: "Sunshine Group",
  },
  {
    kst: 36363,
    department: "Business Development",
    locked: false,
    group: "Group A",
    company: "XYZ Industries",
  },
  {
    kst: 48914,
    department: "Accounting",
    locked: false,
    group: "Group C",
    company: "Acme Corporation",
  },
  {
    kst: 66390,
    department: "Accounting",
    locked: false,
    group: "Group E",
    company: "XYZ Industries",
  },
  {
    kst: 95609,
    department: "Accounting",
    locked: false,
    group: "Group E",
    company: "Global Enterprises",
  },
  {
    kst: 84378,
    department: "Human Resources",
    locked: false,
    group: "Group E",
    company: "Sunshine Group",
  },
  {
    kst: 35508,
    department: "Training",
    locked: true,
    group: "Group A",
    company: "Innovative Solutions",
  },
  {
    kst: 84381,
    department: "Marketing",
    locked: false,
    group: "Group D",
    company: "Innovative Solutions",
  },
  {
    kst: 79842,
    department: "Research and Development",
    locked: false,
    group: "Group B",
    company: "Acme Corporation",
  },
  {
    kst: 70667,
    department: "Product Management",
    locked: false,
    group: "Group G",
    company: "Acme Corporation",
  },
  {
    kst: 96331,
    department: "Sales",
    locked: true,
    group: "Group A",
    company: "Global Enterprises",
  },
  {
    kst: 56405,
    department: "Engineering",
    locked: false,
    group: "Group F",
    company: "Sunshine Group",
  },
  {
    kst: 61680,
    department: "Accounting",
    locked: true,
    group: "Group J",
    company: "Acme Corporation",
  },
  {
    kst: 87387,
    department: "Sales",
    locked: false,
    group: "Group F",
    company: "XYZ Industries",
  },
  {
    kst: 12265,
    department: "Services",
    locked: true,
    group: "Group J",
    company: "Sunshine Group",
  },
  {
    kst: 15880,
    department: "Research and Development",
    locked: true,
    group: "Group G",
    company: "Sunshine Group",
  },
  {
    kst: 91382,
    department: "Legal",
    locked: false,
    group: "Group D",
    company: "Sunshine Group",
  },
  {
    kst: 48723,
    department: "Business Development",
    locked: true,
    group: "Group D",
    company: "Innovative Solutions",
  },
  {
    kst: 91082,
    department: "Sales",
    locked: false,
    group: "Group E",
    company: "Acme Corporation",
  },
  {
    kst: 56883,
    department: "Product Management",
    locked: true,
    group: "Group C",
    company: "XYZ Industries",
  },
  {
    kst: 43629,
    department: "Human Resources",
    locked: false,
    group: "Group H",
    company: "XYZ Industries",
  },
  {
    kst: 86194,
    department: "Legal",
    locked: true,
    group: "Group I",
    company: "Acme Corporation",
  },
  {
    kst: 22634,
    department: "Business Development",
    locked: false,
    group: "Group I",
    company: "Global Enterprises",
  },
  {
    kst: 37850,
    department: "Support",
    locked: true,
    group: "Group J",
    company: "Innovative Solutions",
  },
  {
    kst: 58926,
    department: "Services",
    locked: false,
    group: "Group A",
    company: "XYZ Industries",
  },
  {
    kst: 51777,
    department: "Business Development",
    locked: true,
    group: "Group H",
    company: "Innovative Solutions",
  },
  {
    kst: 63900,
    department: "Sales",
    locked: false,
    group: "Group H",
    company: "Sunshine Group",
  },
  {
    kst: 18460,
    department: "Product Management",
    locked: false,
    group: "Group E",
    company: "Sunshine Group",
  },
  {
    kst: 38501,
    department: "Services",
    locked: true,
    group: "Group G",
    company: "XYZ Industries",
  },
  {
    kst: 45523,
    department: "Legal",
    locked: false,
    group: "Group J",
    company: "XYZ Industries",
  },
  {
    kst: 96207,
    department: "Research and Development",
    locked: true,
    group: "Group J",
    company: "Global Enterprises",
  },
  {
    kst: 73117,
    department: "Product Management",
    locked: false,
    group: "Group C",
    company: "Innovative Solutions",
  },
  {
    kst: 38316,
    department: "Services",
    locked: true,
    group: "Group F",
    company: "Innovative Solutions",
  },
  {
    kst: 49109,
    department: "Research and Development",
    locked: true,
    group: "Group J",
    company: "XYZ Industries",
  },
  {
    kst: 92212,
    department: "Accounting",
    locked: false,
    group: "Group C",
    company: "XYZ Industries",
  },
  {
    kst: 67561,
    department: "Legal",
    locked: true,
    group: "Group G",
    company: "Acme Corporation",
  },
  {
    kst: 97539,
    department: "Legal",
    locked: true,
    group: "Group A",
    company: "XYZ Industries",
  },
  {
    kst: 67779,
    department: "Training",
    locked: false,
    group: "Group B",
    company: "Global Enterprises",
  },
  {
    kst: 13633,
    department: "Engineering",
    locked: false,
    group: "Group A",
    company: "Acme Corporation",
  },
  {
    kst: 77092,
    department: "Support",
    locked: true,
    group: "Group F",
    company: "Acme Corporation",
  },
  {
    kst: 10052,
    department: "Accounting",
    locked: true,
    group: "Group D",
    company: "Innovative Solutions",
  },
  {
    kst: 15870,
    department: "Training",
    locked: false,
    group: "Group C",
    company: "XYZ Industries",
  },
  {
    kst: 37115,
    department: "Legal",
    locked: true,
    group: "Group A",
    company: "XYZ Industries",
  },
  {
    kst: 81396,
    department: "Legal",
    locked: true,
    group: "Group C",
    company: "Acme Corporation",
  },
  {
    kst: 57864,
    department: "Accounting",
    locked: false,
    group: "Group F",
    company: "Acme Corporation",
  },
  {
    kst: 86547,
    department: "Sales",
    locked: true,
    group: "Group D",
    company: "Global Enterprises",
  },
  {
    kst: 79939,
    department: "Human Resources",
    locked: true,
    group: "Group C",
    company: "XYZ Industries",
  },
  {
    kst: 84368,
    department: "Training",
    locked: true,
    group: "Group C",
    company: "Acme Corporation",
  },
  {
    kst: 93461,
    department: "Legal",
    locked: false,
    group: "Group A",
    company: "Innovative Solutions",
  },
  {
    kst: 67537,
    department: "Human Resources",
    locked: true,
    group: "Group D",
    company: "Acme Corporation",
  },
  {
    kst: 78677,
    department: "Business Development",
    locked: false,
    group: "Group B",
    company: "Innovative Solutions",
  },
  {
    kst: 92837,
    department: "Research and Development",
    locked: true,
    group: "Group D",
    company: "Innovative Solutions",
  },
  {
    kst: 50461,
    department: "Marketing",
    locked: false,
    group: "Group A",
    company: "Sunshine Group",
  },
  {
    kst: 43814,
    department: "Business Development",
    locked: true,
    group: "Group J",
    company: "Sunshine Group",
  },
  {
    kst: 57141,
    department: "Engineering",
    locked: false,
    group: "Group I",
    company: "Acme Corporation",
  },
  {
    kst: 27800,
    department: "Business Development",
    locked: false,
    group: "Group H",
    company: "Sunshine Group",
  },
  {
    kst: 68024,
    department: "Business Development",
    locked: false,
    group: "Group E",
    company: "XYZ Industries",
  },
  {
    kst: 74492,
    department: "Services",
    locked: false,
    group: "Group I",
    company: "Global Enterprises",
  },
  {
    kst: 47889,
    department: "Engineering",
    locked: true,
    group: "Group I",
    company: "Sunshine Group",
  },
  {
    kst: 72348,
    department: "Product Management",
    locked: true,
    group: "Group J",
    company: "Global Enterprises",
  },
  {
    kst: 31671,
    department: "Legal",
    locked: true,
    group: "Group G",
    company: "Acme Corporation",
  },
  {
    kst: 26794,
    department: "Support",
    locked: false,
    group: "Group B",
    company: "Acme Corporation",
  },
  {
    kst: 39390,
    department: "Services",
    locked: false,
    group: "Group H",
    company: "Sunshine Group",
  },
  {
    kst: 18585,
    department: "Business Development",
    locked: true,
    group: "Group A",
    company: "Acme Corporation",
  },
  {
    kst: 94361,
    department: "Legal",
    locked: false,
    group: "Group C",
    company: "Sunshine Group",
  },
  {
    kst: 37149,
    department: "Marketing",
    locked: true,
    group: "Group B",
    company: "Sunshine Group",
  },
  {
    kst: 17563,
    department: "Human Resources",
    locked: false,
    group: "Group I",
    company: "Acme Corporation",
  },
  {
    kst: 67074,
    department: "Human Resources",
    locked: false,
    group: "Group G",
    company: "Acme Corporation",
  },
  {
    kst: 15217,
    department: "Business Development",
    locked: true,
    group: "Group H",
    company: "XYZ Industries",
  },
  {
    kst: 19502,
    department: "Marketing",
    locked: true,
    group: "Group H",
    company: "XYZ Industries",
  },
  {
    kst: 85567,
    department: "Marketing",
    locked: false,
    group: "Group G",
    company: "Acme Corporation",
  },
  {
    kst: 92428,
    department: "Services",
    locked: true,
    group: "Group D",
    company: "XYZ Industries",
  },
  {
    kst: 21879,
    department: "Legal",
    locked: true,
    group: "Group C",
    company: "XYZ Industries",
  },
  {
    kst: 75732,
    department: "Accounting",
    locked: true,
    group: "Group I",
    company: "Sunshine Group",
  },
  {
    kst: 31984,
    department: "Sales",
    locked: false,
    group: "Group A",
    company: "Innovative Solutions",
  },
  {
    kst: 60179,
    department: "Marketing",
    locked: true,
    group: "Group J",
    company: "XYZ Industries",
  },
  {
    kst: 84479,
    department: "Services",
    locked: false,
    group: "Group F",
    company: "Acme Corporation",
  },
  {
    kst: 79914,
    department: "Business Development",
    locked: false,
    group: "Group H",
    company: "Sunshine Group",
  },
  {
    kst: 16661,
    department: "Research and Development",
    locked: true,
    group: "Group D",
    company: "Global Enterprises",
  },
  {
    kst: 91752,
    department: "Training",
    locked: true,
    group: "Group G",
    company: "Global Enterprises",
  },
  {
    kst: 36590,
    department: "Services",
    locked: true,
    group: "Group E",
    company: "Global Enterprises",
  },
  {
    kst: 36706,
    department: "Sales",
    locked: true,
    group: "Group D",
    company: "Sunshine Group",
  },
  {
    kst: 14301,
    department: "Training",
    locked: true,
    group: "Group C",
    company: "Sunshine Group",
  },
  {
    kst: 91511,
    department: "Research and Development",
    locked: false,
    group: "Group E",
    company: "Innovative Solutions",
  },
  {
    kst: 39754,
    department: "Marketing",
    locked: true,
    group: "Group E",
    company: "Innovative Solutions",
  },
  {
    kst: 26919,
    department: "Support",
    locked: false,
    group: "Group C",
    company: "Innovative Solutions",
  },
  {
    kst: 86644,
    department: "Legal",
    locked: false,
    group: "Group J",
    company: "Sunshine Group",
  },
  {
    kst: 84686,
    department: "Sales",
    locked: true,
    group: "Group A",
    company: "Sunshine Group",
  },
  {
    kst: 45953,
    department: "Business Development",
    locked: true,
    group: "Group J",
    company: "Sunshine Group",
  },
  {
    kst: 77326,
    department: "Services",
    locked: false,
    group: "Group J",
    company: "Acme Corporation",
  },
  {
    kst: 45132,
    department: "Training",
    locked: true,
    group: "Group E",
    company: "Acme Corporation",
  },
  {
    kst: 93176,
    department: "Support",
    locked: false,
    group: "Group I",
    company: "Acme Corporation",
  },
  {
    kst: 23096,
    department: "Services",
    locked: false,
    group: "Group C",
    company: "XYZ Industries",
  },
  {
    kst: 58427,
    department: "Product Management",
    locked: true,
    group: "Group A",
    company: "Acme Corporation",
  },
  {
    kst: 66763,
    department: "Business Development",
    locked: false,
    group: "Group A",
    company: "XYZ Industries",
  },
  {
    kst: 62275,
    department: "Training",
    locked: false,
    group: "Group A",
    company: "Acme Corporation",
  },
  {
    kst: 83262,
    department: "Engineering",
    locked: true,
    group: "Group E",
    company: "Sunshine Group",
  },
  {
    kst: 36285,
    department: "Legal",
    locked: true,
    group: "Group H",
    company: "Sunshine Group",
  },
  {
    kst: 47090,
    department: "Product Management",
    locked: true,
    group: "Group G",
    company: "Global Enterprises",
  },
];
